In [63]:
import numpy as np


In [64]:
venda_valor = [240000,75000,28000,98200,45000,88000]
comissoes = [12,8,4,10,3,5]


In [65]:
arrvenda = np.array(venda_valor)
com = np.array(comissoes)
resultado = arrvenda * (com/100)
print(resultado)

[28800.  6000.  1120.  9820.  1350.  4400.]


In [66]:
#mostra o tipo de daddos que eu tenho dentro do array
arrvenda.dtype

dtype('int32')

In [67]:
arrayint = np.array([1,2,3,4,5,6,7,8,9])
arrayint.dtype

dtype('int32')

In [68]:
array2 = np.array([1,2,3,4,5,6,7,8,9.0])
array2.dtype


dtype('float64')

In [69]:
array3 = np.array([1,2,3,'4',6])
array3.dtype

matrix = np.array([[4000,6500,1500,0],[7000,5000,0,500],[10000,8000,0,2500]])
print(matrix)

[[ 4000  6500  1500     0]
 [ 7000  5000     0   500]
 [10000  8000     0  2500]]


In [70]:
matrix.shape

(3, 4)

In [71]:
matrix[2][0]

10000

In [75]:
#Calculando a media de um array
np.mean(matrix[1])


3250.0

In [76]:
np.median(matrix)

3250.0

In [83]:
array4 = np.array([24,85,74,69])
array5 = np.array([85,89,74,76])
#soma
array4 + array5
np.sum(array5)
np.max(array5)
np.min(array5)
array5 * 2
#soma acaumulada 
np.cumsum(array5)

array([ 85, 174, 248, 324])